name: My-CI

on: 
   push:
    branches: [ "main" ]
   pull_request:
    branches: [ "main" ]

   workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
       - uses: actions/checkout@v4

       - name: My-Name
         run: echo Srikanth

       - name: My-Father
         run: echo Veera
     
    
    
   
